// <auto-generated />
using System;
using Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240612060651_PurchaseOrder_SeedAdded")]
    partial class PurchaseOrder_SeedAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.PurchaseOrders.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "Asus Vivobook i5",
                            UnitPrice = 80m
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Asus Vivobook i7",
                            UnitPrice = 90m
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Asus Vivobook i9",
                            UnitPrice = 100m
                        },
                        new
                        {
                            ProductId = 4,
                            Name = "Lenovo IdeaPad Flex 5",
                            UnitPrice = 110m
                        },
                        new
                        {
                            ProductId = 5,
                            Name = "Lenovo IdeaPad 1 AMD Ryzen 5",
                            UnitPrice = 120m
                        },
                        new
                        {
                            ProductId = 6,
                            Name = "Apple MacBook Pro 14 inch M3",
                            UnitPrice = 210m
                        },
                        new
                        {
                            ProductId = 7,
                            Name = "Apple MacBook Pro 15 inch M1",
                            UnitPrice = 190m
                        },
                        new
                        {
                            ProductId = 8,
                            Name = "Dell Inspiron 3530 Core i3",
                            UnitPrice = 60m
                        },
                        new
                        {
                            ProductId = 9,
                            Name = "Dell Vostro 5620 Core i5",
                            UnitPrice = 70m
                        });
                });

            modelBuilder.Entity("Entities.Models.PurchaseOrders.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PurchaseOrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("PurchaseOrderId");

                    b.ToTable("PurchaseOrders");

                    b.HasData(
                        new
                        {
                            PurchaseOrderId = 1,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5068),
                            PurchaseOrderDate = new DateTime(2024, 6, 11, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(4588),
                            PurchaseOrderNumber = "PO001",
                            ReferenceId = 1,
                            Remarks = "Remark 1",
                            SupplierId = 2
                        },
                        new
                        {
                            PurchaseOrderId = 2,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5482),
                            PurchaseOrderDate = new DateTime(2024, 6, 10, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5467),
                            PurchaseOrderNumber = "PO002",
                            ReferenceId = 2,
                            Remarks = "Remark 2",
                            SupplierId = 3
                        },
                        new
                        {
                            PurchaseOrderId = 3,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5506),
                            PurchaseOrderDate = new DateTime(2024, 6, 9, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5505),
                            PurchaseOrderNumber = "PO003",
                            ReferenceId = 3,
                            Remarks = "Remark 3",
                            SupplierId = 1
                        },
                        new
                        {
                            PurchaseOrderId = 4,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5513),
                            PurchaseOrderDate = new DateTime(2024, 6, 8, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5512),
                            PurchaseOrderNumber = "PO004",
                            ReferenceId = 4,
                            Remarks = "Remark 4",
                            SupplierId = 2
                        },
                        new
                        {
                            PurchaseOrderId = 5,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5520),
                            PurchaseOrderDate = new DateTime(2024, 6, 7, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5519),
                            PurchaseOrderNumber = "PO005",
                            ReferenceId = 5,
                            Remarks = "Remark 5",
                            SupplierId = 3
                        },
                        new
                        {
                            PurchaseOrderId = 6,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5529),
                            PurchaseOrderDate = new DateTime(2024, 6, 6, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5527),
                            PurchaseOrderNumber = "PO006",
                            ReferenceId = 6,
                            Remarks = "Remark 6",
                            SupplierId = 1
                        },
                        new
                        {
                            PurchaseOrderId = 7,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5535),
                            PurchaseOrderDate = new DateTime(2024, 6, 5, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5534),
                            PurchaseOrderNumber = "PO007",
                            ReferenceId = 7,
                            Remarks = "Remark 7",
                            SupplierId = 2
                        },
                        new
                        {
                            PurchaseOrderId = 8,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5541),
                            PurchaseOrderDate = new DateTime(2024, 6, 4, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5540),
                            PurchaseOrderNumber = "PO008",
                            ReferenceId = 8,
                            Remarks = "Remark 8",
                            SupplierId = 3
                        },
                        new
                        {
                            PurchaseOrderId = 9,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5547),
                            PurchaseOrderDate = new DateTime(2024, 6, 3, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5546),
                            PurchaseOrderNumber = "PO009",
                            ReferenceId = 9,
                            Remarks = "Remark 9",
                            SupplierId = 1
                        },
                        new
                        {
                            PurchaseOrderId = 10,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5556),
                            PurchaseOrderDate = new DateTime(2024, 6, 2, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5555),
                            PurchaseOrderNumber = "PO010",
                            ReferenceId = 10,
                            Remarks = "Remark 10",
                            SupplierId = 2
                        },
                        new
                        {
                            PurchaseOrderId = 11,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5563),
                            PurchaseOrderDate = new DateTime(2024, 6, 1, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5562),
                            PurchaseOrderNumber = "PO011",
                            ReferenceId = 11,
                            Remarks = "Remark 11",
                            SupplierId = 3
                        },
                        new
                        {
                            PurchaseOrderId = 12,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5569),
                            PurchaseOrderDate = new DateTime(2024, 5, 31, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5568),
                            PurchaseOrderNumber = "PO012",
                            ReferenceId = 12,
                            Remarks = "Remark 12",
                            SupplierId = 1
                        },
                        new
                        {
                            PurchaseOrderId = 13,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5575),
                            PurchaseOrderDate = new DateTime(2024, 5, 30, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5573),
                            PurchaseOrderNumber = "PO013",
                            ReferenceId = 13,
                            Remarks = "Remark 13",
                            SupplierId = 2
                        },
                        new
                        {
                            PurchaseOrderId = 14,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5581),
                            PurchaseOrderDate = new DateTime(2024, 5, 29, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5579),
                            PurchaseOrderNumber = "PO014",
                            ReferenceId = 14,
                            Remarks = "Remark 14",
                            SupplierId = 3
                        },
                        new
                        {
                            PurchaseOrderId = 15,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5587),
                            PurchaseOrderDate = new DateTime(2024, 5, 28, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5586),
                            PurchaseOrderNumber = "PO015",
                            ReferenceId = 15,
                            Remarks = "Remark 15",
                            SupplierId = 1
                        },
                        new
                        {
                            PurchaseOrderId = 16,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5593),
                            PurchaseOrderDate = new DateTime(2024, 5, 27, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5592),
                            PurchaseOrderNumber = "PO016",
                            ReferenceId = 16,
                            Remarks = "Remark 16",
                            SupplierId = 2
                        },
                        new
                        {
                            PurchaseOrderId = 17,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5599),
                            PurchaseOrderDate = new DateTime(2024, 5, 26, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5597),
                            PurchaseOrderNumber = "PO017",
                            ReferenceId = 17,
                            Remarks = "Remark 17",
                            SupplierId = 3
                        },
                        new
                        {
                            PurchaseOrderId = 18,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5606),
                            PurchaseOrderDate = new DateTime(2024, 5, 25, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5604),
                            PurchaseOrderNumber = "PO018",
                            ReferenceId = 18,
                            Remarks = "Remark 18",
                            SupplierId = 1
                        },
                        new
                        {
                            PurchaseOrderId = 19,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5611),
                            PurchaseOrderDate = new DateTime(2024, 5, 24, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5610),
                            PurchaseOrderNumber = "PO019",
                            ReferenceId = 19,
                            Remarks = "Remark 19",
                            SupplierId = 2
                        },
                        new
                        {
                            PurchaseOrderId = 20,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5618),
                            PurchaseOrderDate = new DateTime(2024, 5, 23, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5616),
                            PurchaseOrderNumber = "PO020",
                            ReferenceId = 20,
                            Remarks = "Remark 20",
                            SupplierId = 3
                        },
                        new
                        {
                            PurchaseOrderId = 21,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5624),
                            PurchaseOrderDate = new DateTime(2024, 5, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5622),
                            PurchaseOrderNumber = "PO021",
                            ReferenceId = 21,
                            Remarks = "Remark 21",
                            SupplierId = 1
                        },
                        new
                        {
                            PurchaseOrderId = 22,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5629),
                            PurchaseOrderDate = new DateTime(2024, 5, 21, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5628),
                            PurchaseOrderNumber = "PO022",
                            ReferenceId = 22,
                            Remarks = "Remark 22",
                            SupplierId = 2
                        },
                        new
                        {
                            PurchaseOrderId = 23,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5680),
                            PurchaseOrderDate = new DateTime(2024, 5, 20, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5678),
                            PurchaseOrderNumber = "PO023",
                            ReferenceId = 23,
                            Remarks = "Remark 23",
                            SupplierId = 3
                        },
                        new
                        {
                            PurchaseOrderId = 24,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5686),
                            PurchaseOrderDate = new DateTime(2024, 5, 19, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5685),
                            PurchaseOrderNumber = "PO024",
                            ReferenceId = 24,
                            Remarks = "Remark 24",
                            SupplierId = 1
                        },
                        new
                        {
                            PurchaseOrderId = 25,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5692),
                            PurchaseOrderDate = new DateTime(2024, 5, 18, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5691),
                            PurchaseOrderNumber = "PO025",
                            ReferenceId = 25,
                            Remarks = "Remark 25",
                            SupplierId = 2
                        },
                        new
                        {
                            PurchaseOrderId = 26,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5698),
                            PurchaseOrderDate = new DateTime(2024, 5, 17, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5697),
                            PurchaseOrderNumber = "PO026",
                            ReferenceId = 26,
                            Remarks = "Remark 26",
                            SupplierId = 3
                        },
                        new
                        {
                            PurchaseOrderId = 27,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5704),
                            PurchaseOrderDate = new DateTime(2024, 5, 16, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5703),
                            PurchaseOrderNumber = "PO027",
                            ReferenceId = 27,
                            Remarks = "Remark 27",
                            SupplierId = 1
                        },
                        new
                        {
                            PurchaseOrderId = 28,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5710),
                            PurchaseOrderDate = new DateTime(2024, 5, 15, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5708),
                            PurchaseOrderNumber = "PO028",
                            ReferenceId = 28,
                            Remarks = "Remark 28",
                            SupplierId = 2
                        },
                        new
                        {
                            PurchaseOrderId = 29,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5716),
                            PurchaseOrderDate = new DateTime(2024, 5, 14, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5715),
                            PurchaseOrderNumber = "PO029",
                            ReferenceId = 29,
                            Remarks = "Remark 29",
                            SupplierId = 3
                        },
                        new
                        {
                            PurchaseOrderId = 30,
                            ExpectedDate = new DateTime(2024, 6, 22, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5722),
                            PurchaseOrderDate = new DateTime(2024, 5, 13, 12, 6, 50, 932, DateTimeKind.Local).AddTicks(5721),
                            PurchaseOrderNumber = "PO030",
                            ReferenceId = 30,
                            Remarks = "Remark 30",
                            SupplierId = 1
                        });
                });

            modelBuilder.Entity("Entities.Models.PurchaseOrders.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("PurchaseOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LineItemId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseOrderDetailId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderDetails");

                    b.HasData(
                        new
                        {
                            PurchaseOrderDetailId = 1,
                            LineItemId = 3,
                            PurchaseOrderId = 1,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 2,
                            LineItemId = 4,
                            PurchaseOrderId = 1,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 3,
                            LineItemId = 5,
                            PurchaseOrderId = 1,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 4,
                            LineItemId = 4,
                            PurchaseOrderId = 2,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 5,
                            LineItemId = 5,
                            PurchaseOrderId = 2,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 6,
                            LineItemId = 6,
                            PurchaseOrderId = 2,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 7,
                            LineItemId = 5,
                            PurchaseOrderId = 3,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 8,
                            LineItemId = 6,
                            PurchaseOrderId = 3,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 9,
                            LineItemId = 7,
                            PurchaseOrderId = 3,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 10,
                            LineItemId = 6,
                            PurchaseOrderId = 4,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 11,
                            LineItemId = 7,
                            PurchaseOrderId = 4,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 12,
                            LineItemId = 8,
                            PurchaseOrderId = 4,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 13,
                            LineItemId = 7,
                            PurchaseOrderId = 5,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 14,
                            LineItemId = 8,
                            PurchaseOrderId = 5,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 15,
                            LineItemId = 9,
                            PurchaseOrderId = 5,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 16,
                            LineItemId = 8,
                            PurchaseOrderId = 6,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 17,
                            LineItemId = 9,
                            PurchaseOrderId = 6,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 18,
                            LineItemId = 1,
                            PurchaseOrderId = 6,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 19,
                            LineItemId = 9,
                            PurchaseOrderId = 7,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 20,
                            LineItemId = 1,
                            PurchaseOrderId = 7,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 21,
                            LineItemId = 2,
                            PurchaseOrderId = 7,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 22,
                            LineItemId = 1,
                            PurchaseOrderId = 8,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 23,
                            LineItemId = 2,
                            PurchaseOrderId = 8,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 24,
                            LineItemId = 3,
                            PurchaseOrderId = 8,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 25,
                            LineItemId = 2,
                            PurchaseOrderId = 9,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 26,
                            LineItemId = 3,
                            PurchaseOrderId = 9,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 27,
                            LineItemId = 4,
                            PurchaseOrderId = 9,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 28,
                            LineItemId = 3,
                            PurchaseOrderId = 10,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 29,
                            LineItemId = 4,
                            PurchaseOrderId = 10,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 30,
                            LineItemId = 5,
                            PurchaseOrderId = 10,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 31,
                            LineItemId = 4,
                            PurchaseOrderId = 11,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 32,
                            LineItemId = 5,
                            PurchaseOrderId = 11,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 33,
                            LineItemId = 6,
                            PurchaseOrderId = 11,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 34,
                            LineItemId = 5,
                            PurchaseOrderId = 12,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 35,
                            LineItemId = 6,
                            PurchaseOrderId = 12,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 36,
                            LineItemId = 7,
                            PurchaseOrderId = 12,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 37,
                            LineItemId = 6,
                            PurchaseOrderId = 13,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 38,
                            LineItemId = 7,
                            PurchaseOrderId = 13,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 39,
                            LineItemId = 8,
                            PurchaseOrderId = 13,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 40,
                            LineItemId = 7,
                            PurchaseOrderId = 14,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 41,
                            LineItemId = 8,
                            PurchaseOrderId = 14,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 42,
                            LineItemId = 9,
                            PurchaseOrderId = 14,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 43,
                            LineItemId = 8,
                            PurchaseOrderId = 15,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 44,
                            LineItemId = 9,
                            PurchaseOrderId = 15,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 45,
                            LineItemId = 1,
                            PurchaseOrderId = 15,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 46,
                            LineItemId = 9,
                            PurchaseOrderId = 16,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 47,
                            LineItemId = 1,
                            PurchaseOrderId = 16,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 48,
                            LineItemId = 2,
                            PurchaseOrderId = 16,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 49,
                            LineItemId = 1,
                            PurchaseOrderId = 17,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 50,
                            LineItemId = 2,
                            PurchaseOrderId = 17,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 51,
                            LineItemId = 3,
                            PurchaseOrderId = 17,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 52,
                            LineItemId = 2,
                            PurchaseOrderId = 18,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 53,
                            LineItemId = 3,
                            PurchaseOrderId = 18,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 54,
                            LineItemId = 4,
                            PurchaseOrderId = 18,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 55,
                            LineItemId = 3,
                            PurchaseOrderId = 19,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 56,
                            LineItemId = 4,
                            PurchaseOrderId = 19,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 57,
                            LineItemId = 5,
                            PurchaseOrderId = 19,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 58,
                            LineItemId = 4,
                            PurchaseOrderId = 20,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 59,
                            LineItemId = 5,
                            PurchaseOrderId = 20,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 60,
                            LineItemId = 6,
                            PurchaseOrderId = 20,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 61,
                            LineItemId = 5,
                            PurchaseOrderId = 21,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 62,
                            LineItemId = 6,
                            PurchaseOrderId = 21,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 63,
                            LineItemId = 7,
                            PurchaseOrderId = 21,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 64,
                            LineItemId = 6,
                            PurchaseOrderId = 22,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 65,
                            LineItemId = 7,
                            PurchaseOrderId = 22,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 66,
                            LineItemId = 8,
                            PurchaseOrderId = 22,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 67,
                            LineItemId = 7,
                            PurchaseOrderId = 23,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 68,
                            LineItemId = 8,
                            PurchaseOrderId = 23,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 69,
                            LineItemId = 9,
                            PurchaseOrderId = 23,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 70,
                            LineItemId = 8,
                            PurchaseOrderId = 24,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 71,
                            LineItemId = 9,
                            PurchaseOrderId = 24,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 72,
                            LineItemId = 1,
                            PurchaseOrderId = 24,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 73,
                            LineItemId = 9,
                            PurchaseOrderId = 25,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 74,
                            LineItemId = 1,
                            PurchaseOrderId = 25,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 75,
                            LineItemId = 2,
                            PurchaseOrderId = 25,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 76,
                            LineItemId = 1,
                            PurchaseOrderId = 26,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 77,
                            LineItemId = 2,
                            PurchaseOrderId = 26,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 78,
                            LineItemId = 3,
                            PurchaseOrderId = 26,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 79,
                            LineItemId = 2,
                            PurchaseOrderId = 27,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 80,
                            LineItemId = 3,
                            PurchaseOrderId = 27,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 81,
                            LineItemId = 4,
                            PurchaseOrderId = 27,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 82,
                            LineItemId = 3,
                            PurchaseOrderId = 28,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 83,
                            LineItemId = 4,
                            PurchaseOrderId = 28,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 84,
                            LineItemId = 5,
                            PurchaseOrderId = 28,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 85,
                            LineItemId = 4,
                            PurchaseOrderId = 29,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 86,
                            LineItemId = 5,
                            PurchaseOrderId = 29,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 87,
                            LineItemId = 6,
                            PurchaseOrderId = 29,
                            Quantity = 40,
                            Rate = 82.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 88,
                            LineItemId = 5,
                            PurchaseOrderId = 30,
                            Quantity = 20,
                            Rate = 41.0m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 89,
                            LineItemId = 6,
                            PurchaseOrderId = 30,
                            Quantity = 30,
                            Rate = 61.5m
                        },
                        new
                        {
                            PurchaseOrderDetailId = 90,
                            LineItemId = 7,
                            PurchaseOrderId = 30,
                            Quantity = 40,
                            Rate = 82.0m
                        });
                });

            modelBuilder.Entity("Entities.Models.PurchaseOrders.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Address = "583 Wall Dr. Gwynn Oak, MD 21207",
                            Name = "Insight"
                        },
                        new
                        {
                            SupplierId = 2,
                            Address = "312 Forest Avenue, BF 923",
                            Name = "Micro Center"
                        },
                        new
                        {
                            SupplierId = 3,
                            Address = "345 Street Forest Avenue, BF 923",
                            Name = "Computer Source"
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Entities.Models.PurchaseOrders.PurchaseOrderDetail", b =>
                {
                    b.HasOne("Entities.Models.PurchaseOrders.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
